### ISSUE TITLE
Support for AsciiDoc

### ISSUE THREAD

**Issue by zhouyaoji** [zalando-incubator/gitbook-structured-toc#3]
Gitbook can also render AsciiDoc to HTML. I have used your plugin for documentation in Markdown, but am not working on documentation authored in AsciiDoc. I also think AsciiDoc is better for writing technical documentation. 

The AsciiDoc syntax for headings uses the equal sign instead of a hash:

= Heading Level 1

== Heading Level 2

=== Heading Level 3

**Comment by fmueller** [comment]
Sorry for coming back to you so late. Support for AsciiDoc is surely a great improvement on this plugin. Can you provide a pull request for it?

**Comment by LappleApple** [comment]
@fmueller +1
